// frontend/src/components/steps/Step4Results.tsx
import { useMemo, useState } from 'react'
import { AlertTriangle, FileSpreadsheet, Loader2 } from 'lucide-react'
import { urls } from '@/api/client'
import { useAppStore } from '@/store/useAppStore'
import type { Fila } from '@/types'

const pct = (v?: number | null) => (v == null ? '0.0%' : `${(v * 100).toFixed(1)}%`)
const lista = (v: unknown) => (Array.isArray(v) ? v.join(', ') || '—' : String(v || '—'))

function nivelClass(nivel?: string): string {
  switch (String(nivel).toLowerCase()) {
    case 'cumple': return 'bg-emerald-100 text-emerald-800'
    case 'parcial': return 'bg-amber-100 text-amber-800'
    case 'omision': return 'bg-rose-100 text-rose-800'
    default: return 'bg-slate-100 text-slate-800'
  }
}

function Kpi({ etiqueta, valor, color }: { etiqueta: string; valor: string | number; color: string }) {
  return (
    <div className="p-4 rounded-xl bg-surface border border-border shadow-sm">
      <span className="text-xs text-content-muted font-medium block">{etiqueta}</span>
      <span className={`text-2xl sm:text-3xl font-bold font-mono mt-1 block ${color}`}>{valor}</span>
    </div>
  )
}

function Revision({ fila }: { fila: Fila }) {
  return fila.requiere_revision_manual ? (
    <span className="px-2 py-0.5 rounded bg-amber-100 text-amber-900 font-bold text-[10px]">⚠️ Revisar</span>
  ) : (
    <span className="text-slate-400">—</span>
  )
}

export default function Step4Results() {
  const isComparing = useAppStore((s) => s.isComparing)
  const progressLabel = useAppStore((s) => s.progressLabel)
  const progressPct = useAppStore((s) => s.progressPct)
  const run = useAppStore((s) => s.runStatus)
  const runId = useAppStore((s) => s.activeRunId)
  const soloRevision = useAppStore((s) => s.filterSoloRevision)
  const set = useAppStore((s) => s.set)
  const [tab, setTab] = useState<'via1' | 'via2'>('via1')

  const v1 = useMemo(
    () => (run?.vista_manual ?? []).filter((r) => !soloRevision || r.requiere_revision_manual),
    [run, soloRevision],
  )
  const v2 = useMemo(
    () => (run?.vista_normativa ?? []).filter((r) => !soloRevision || r.requiere_revision_manual),
    [run, soloRevision],
  )

  const th = 'py-2.5 px-3'
  const thead = 'bg-slate-100/70 border-b border-border text-slate-700 font-semibold uppercase text-[10px]'
  const tabBtn = (activa: boolean) =>
    `py-3 px-5 transition border-b-2 ${activa ? 'border-primary text-primary bg-white' : 'border-transparent text-content-muted hover:text-content-main'}`

  return (
    <div className="space-y-6">
      {isComparing && (
        <div className="bg-surface p-6 rounded-xl border border-primary/30 shadow-md space-y-4">
          <div className="flex items-center justify-between text-xs sm:text-sm">
            <span className="font-bold text-primary flex items-center gap-2">
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>{progressLabel || 'Analizando cumplimiento normativo...'}</span>
            </span>
            <span className="font-mono font-bold text-primary">{progressPct}%</span>
          </div>
          <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
            <div className="bg-primary h-2.5 rounded-full transition-all duration-300" style={{ width: `${progressPct}%` }} />
          </div>
        </div>
      )}

      {run && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
            <Kpi etiqueta="🎯 Cobertura Global" valor={pct(run.cobertura_global)} color="text-primary" />
            <Kpi etiqueta="Artículos en Alcance" valor={run.total || run.vista_normativa.length} color="text-content-main" />
            <Kpi etiqueta="Artículos Cubiertos" valor={run.vista_normativa.filter((a) => a.cubierto).length} color="text-emerald-600" />
            {/* "Cubiertos" cuenta el veredicto de adopción de la Vía 2; un artículo con cobertura
                parcial no entra ahí ni en "Huérfanos", así que necesita su propia tarjeta. */}
            <Kpi etiqueta="Cobertura Parcial" valor={(run.articulos_parciales ?? []).length} color="text-amber-600" />
            <Kpi etiqueta="Sin Cobertura (Huérfanos)" valor={run.articulos_sin_cobertura.length} color="text-rose-600" />
          </div>

          {run.alerta_cobertura && (
            <div className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-900 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-sm">
              <div className="flex items-center space-x-2.5">
                <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0" />
                <span className="text-xs sm:text-sm font-semibold">{run.alerta_cobertura}</span>
              </div>
              <span className="text-xs bg-rose-200/80 text-rose-950 font-bold px-2 py-1 rounded">Requiere Atención</span>
            </div>
          )}

          <div className="bg-surface p-4 rounded-xl border border-border shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div className="flex items-center space-x-2.5">
              <input
                id="chk_rev"
                type="checkbox"
                checked={soloRevision}
                onChange={(e) => set({ filterSoloRevision: e.target.checked })}
                className="rounded text-amber-600 focus:ring-amber-500 w-4 h-4 cursor-pointer"
              />
              <label htmlFor="chk_rev" className="text-xs sm:text-sm font-semibold text-content-main cursor-pointer flex items-center gap-1.5">
                <span>Solo filas que requieren revisión manual</span>
                <span className="px-2 py-0.5 rounded-full bg-amber-100 text-amber-800 text-xs font-bold border border-amber-300">
                  {run.total_revision_manual}
                </span>
              </label>
            </div>

            {runId && (
              <div className="flex items-center space-x-2 w-full sm:w-auto">
                <a
                  href={urls.export(runId, 'excel')}
                  download
                  className="flex-1 sm:flex-none px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold flex items-center justify-center gap-2 shadow-sm transition"
                >
                  <FileSpreadsheet className="w-4 h-4" />
                  <span>Papel de Trabajo Excel (6 Hojas)</span>
                </a>
                <a
                  href={urls.export(runId, 'json')}
                  download
                  className="px-3 py-2 rounded-lg border border-border hover:bg-slate-50 text-xs font-semibold text-content-main transition"
                >
                  JSON
                </a>
              </div>
            )}
          </div>

          <div className="bg-surface rounded-xl border border-border shadow-sm overflow-hidden">
            <div className="flex border-b border-border bg-slate-50 text-xs font-bold">
              <button onClick={() => setTab('via1')} className={tabBtn(tab === 'via1')}>📋 Por Sección (Vía 1: Manual → Normativa)</button>
              <button onClick={() => setTab('via2')} className={tabBtn(tab === 'via2')}>📜 Por Artículo (Vía 2: Normativa → Manual)</button>
            </div>

            {tab === 'via1' ? (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className={thead}>
                    <tr>
                      <th className={th}>Jerarquía</th><th className={th}>Sección</th><th className={th}>Nivel Cumplimiento</th>
                      <th className={th}>Artículos</th><th className={th}>Revisión</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {v1.map((row) => (
                      <tr key={row.chunk_id} className="hover:bg-slate-50 transition">
                        <td className="py-2.5 px-3 font-mono font-medium">{row.jerarquia}</td>
                        <td className="py-2.5 px-3 font-medium text-content-main">{row.titulo_seccion}</td>
                        <td className="py-2.5 px-3">
                          <span className={`px-2 py-0.5 rounded text-[11px] font-bold uppercase ${nivelClass(row.nivel_cumplimiento)}`}>
                            {row.nivel_cumplimiento}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 font-mono">{lista(row.articulos)}</td>
                        <td className="py-2.5 px-3"><Revision fila={row} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className={thead}>
                    <tr>
                      <th className={th}>Normativa</th><th className={th}>Artículo</th><th className={th}>Epígrafe</th>
                      <th className={th}>Cobertura</th><th className={th}>Revisión</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {v2.map((row) => (
                      <tr key={row.element_id} className="hover:bg-slate-50 transition">
                        <td className="py-2.5 px-3 font-mono">{row.articulo_doc_id}</td>
                        <td className="py-2.5 px-3 font-bold font-mono text-emerald-800">Art. {row.numero}</td>
                        <td className="py-2.5 px-3 font-medium text-content-main">{row.encabezado}</td>
                        <td className="py-2.5 px-3">
                          <span className={`px-2 py-0.5 rounded text-[11px] font-bold ${row.cubierto ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                            {row.cubierto ? 'Cubierto' : 'No Cubierto'}
                          </span>
                        </td>
                        <td className="py-2.5 px-3"><Revision fila={row} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  )
}

// frontend/src/components/steps/Step4Results.vue
<template>
  <div class="space-y-6">
    <!-- Estado de Progreso en Vivo (SSE) -->
    <div
      v-if="store.isComparing"
      class="bg-surface p-6 rounded-xl border border-primary/30 shadow-md space-y-4 animate-pulse"
    >
      <div class="flex items-center justify-between text-xs sm:text-sm">
        <span class="font-bold text-primary flex items-center gap-2">
          <Loader2 class="w-4 h-4 animate-spin" />
          <span>{{ store.progressLabel || 'Analizando cumplimiento normativo...' }}</span>
        </span>
        <span class="font-mono font-bold text-primary">{{ store.progressPct }}%</span>
      </div>
      <div class="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
        <div
          class="bg-primary h-2.5 rounded-full transition-all duration-300"
          :style="{ width: `${store.progressPct}%` }"
        ></div>
      </div>
    </div>

    <!-- Resultados y KPIs -->
    <template v-if="store.runStatus">
      <!-- Tarjetas de Cobertura Global (Ítem 6) -->
      <div class="grid grid-cols-2 lg:grid-cols-5 gap-4">
        <div class="p-4 rounded-xl bg-surface border border-border shadow-sm">
          <span class="text-xs text-content-muted font-medium block">🎯 Cobertura Global</span>
          <span class="text-2xl sm:text-3xl font-bold text-primary font-mono mt-1 block">
            {{ formatPercent(store.runStatus.cobertura_global) }}
          </span>
        </div>

        <div class="p-4 rounded-xl bg-surface border border-border shadow-sm">
          <span class="text-xs text-content-muted font-medium block">Artículos en Alcance</span>
          <span class="text-2xl sm:text-3xl font-bold text-content-main font-mono mt-1 block">
            {{ store.runStatus.total || store.runStatus.vista_normativa.length }}
          </span>
        </div>

        <div class="p-4 rounded-xl bg-surface border border-border shadow-sm">
          <span class="text-xs text-content-muted font-medium block">Artículos Cubiertos</span>
          <span class="text-2xl sm:text-3xl font-bold text-emerald-600 font-mono mt-1 block">
            {{ store.runStatus.vista_normativa.filter(a => a.cubierto).length }}
          </span>
        </div>

        <!--
          "Cubiertos" cuenta el veredicto de adopción de la Vía 2, no que exista alguna
          sección relacionada. Un artículo con cobertura parcial no entra ahí ni en
          "Huérfanos": necesita su propia tarjeta o desaparece del resumen.
        -->
        <div class="p-4 rounded-xl bg-surface border border-border shadow-sm">
          <span class="text-xs text-content-muted font-medium block">Cobertura Parcial</span>
          <span class="text-2xl sm:text-3xl font-bold text-amber-600 font-mono mt-1 block">
            {{ (store.runStatus.articulos_parciales ?? []).length }}
          </span>
        </div>

        <div class="p-4 rounded-xl bg-surface border border-border shadow-sm">
          <span class="text-xs text-content-muted font-medium block">Sin Cobertura (Huérfanos)</span>
          <span class="text-2xl sm:text-3xl font-bold text-rose-600 font-mono mt-1 block">
            {{ store.runStatus.articulos_sin_cobertura.length }}
          </span>
        </div>
      </div>

      <!-- Alerta de Cobertura Incompleta (Premisa Bloque A) -->
      <div
        v-if="store.runStatus.alerta_cobertura"
        class="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-900 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-sm"
      >
        <div class="flex items-center space-x-2.5">
          <AlertTriangle class="w-5 h-5 text-rose-600 shrink-0" />
          <span class="text-xs sm:text-sm font-semibold">{{ store.runStatus.alerta_cobertura }}</span>
        </div>
        <span class="text-xs bg-rose-200/80 text-rose-950 font-bold px-2 py-1 rounded">Requiere Atención</span>
      </div>

      <!-- Barra de Filtros y Descargas -->
      <div class="bg-surface p-4 rounded-xl border border-border shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <!-- Filtro Revisión Manual (Ítem 10) -->
        <div class="flex items-center space-x-2.5">
          <input
            v-model="store.filterSoloRevision"
            type="checkbox"
            id="chk_rev"
            class="rounded text-amber-600 focus:ring-amber-500 w-4 h-4 cursor-pointer"
          />
          <label for="chk_rev" class="text-xs sm:text-sm font-semibold text-content-main cursor-pointer flex items-center gap-1.5">
            <span>Solo filas que requieren revisión manual</span>
            <span class="px-2 py-0.5 rounded-full bg-amber-100 text-amber-800 text-xs font-bold border border-amber-300">
              {{ store.runStatus.total_revision_manual }}
            </span>
          </label>
        </div>

        <!-- Botones de Exportación -->
        <div class="flex items-center space-x-2 w-full sm:w-auto">
          <a
            :href="`/api/compare/runs/${store.activeRunId}/export/excel`"
            download
            class="flex-1 sm:flex-none px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold flex items-center justify-center gap-2 shadow-sm transition"
          >
            <FileSpreadsheet class="w-4 h-4" />
            <span>Papel de Trabajo Excel (6 Hojas)</span>
          </a>
          <a
            :href="`/api/compare/runs/${store.activeRunId}/export/json`"
            download
            class="px-3 py-2 rounded-lg border border-border hover:bg-slate-50 text-xs font-semibold text-content-main transition"
          >
            JSON
          </a>
        </div>
      </div>

      <!-- Sub-Pestañas Vía 1 y Vía 2 -->
      <div class="bg-surface rounded-xl border border-border shadow-sm overflow-hidden">
        <div class="flex border-b border-border bg-slate-50 text-xs font-bold">
          <button
            @click="activeTab = 'via1'"
            class="py-3 px-5 transition border-b-2"
            :class="activeTab === 'via1' ? 'border-primary text-primary bg-white' : 'border-transparent text-content-muted hover:text-content-main'"
          >
            📋 Por Sección (Vía 1: Manual → Normativa)
          </button>
          <button
            @click="activeTab = 'via2'"
            class="py-3 px-5 transition border-b-2"
            :class="activeTab === 'via2' ? 'border-primary text-primary bg-white' : 'border-transparent text-content-muted hover:text-content-main'"
          >
            📜 Por Artículo (Vía 2: Normativa → Manual)
          </button>
        </div>

        <!-- Tabla Vía 1 -->
        <div v-if="activeTab === 'via1'" class="overflow-x-auto">
          <table class="w-full text-left text-xs">
            <thead class="bg-slate-100/70 border-b border-border text-slate-700 font-semibold uppercase text-[10px]">
              <tr>
                <th class="py-2.5 px-3">Jerarquía</th>
                <th class="py-2.5 px-3">Sección</th>
                <th class="py-2.5 px-3">Nivel Cumplimiento</th>
                <th class="py-2.5 px-3">Artículos</th>
                <th class="py-2.5 px-3">Revisión</th>
                <th class="py-2.5 px-3 text-right">Acción</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-border">
              <tr
                v-for="row in filteredV1"
                :key="row.chunk_id"
                class="hover:bg-slate-50 transition cursor-pointer"
                @click="store.openChunkInspector(row)"
              >
                <td class="py-2.5 px-3 font-mono font-medium">{{ row.jerarquia }}</td>
                <td class="py-2.5 px-3 font-medium text-content-main">{{ row.titulo_seccion }}</td>
                <td class="py-2.5 px-3">
                  <span
                    class="px-2 py-0.5 rounded text-[11px] font-bold uppercase"
                    :class="nivelClass(row.nivel_cumplimiento)"
                  >
                    {{ row.nivel_cumplimiento }}
                  </span>
                </td>
                <td class="py-2.5 px-3 font-mono">{{ formatList(row.articulos) }}</td>
                <td class="py-2.5 px-3">
                  <span
                    v-if="row.requiere_revision_manual"
                    class="px-2 py-0.5 rounded bg-amber-100 text-amber-900 font-bold text-[10px]"
                  >
                    ⚠️ Revisar
                  </span>
                  <span v-else class="text-slate-400">—</span>
                </td>
                <td class="py-2.5 px-3 text-right">
                  <button
                    @click.stop="abrirRowPdf('manual', row)"
                    class="p-1 rounded hover:bg-slate-200 text-primary"
                    title="Ver en PDF"
                  >
                    <ExternalLink class="w-4 h-4" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Tabla Vía 2 -->
        <div v-if="activeTab === 'via2'" class="overflow-x-auto">
          <table class="w-full text-left text-xs">
            <thead class="bg-slate-100/70 border-b border-border text-slate-700 font-semibold uppercase text-[10px]">
              <tr>
                <th class="py-2.5 px-3">Normativa</th>
                <th class="py-2.5 px-3">Artículo</th>
                <th class="py-2.5 px-3">Epígrafe</th>
                <th class="py-2.5 px-3">Cobertura</th>
                <th class="py-2.5 px-3">Revisión</th>
                <th class="py-2.5 px-3 text-right">Acción</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-border">
              <tr
                v-for="row in filteredV2"
                :key="row.element_id"
                class="hover:bg-slate-50 transition cursor-pointer"
                @click="store.openChunkInspector(row)"
              >
                <td class="py-2.5 px-3 font-mono">{{ row.articulo_doc_id }}</td>
                <td class="py-2.5 px-3 font-bold font-mono text-emerald-800">Art. {{ row.numero }}</td>
                <td class="py-2.5 px-3 font-medium text-content-main">{{ row.encabezado }}</td>
                <td class="py-2.5 px-3">
                  <span
                    class="px-2 py-0.5 rounded text-[11px] font-bold"
                    :class="row.cubierto ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'"
                  >
                    {{ row.cubierto ? 'Cubierto' : 'No Cubierto' }}
                  </span>
                </td>
                <td class="py-2.5 px-3">
                  <span
                    v-if="row.requiere_revision_manual"
                    class="px-2 py-0.5 rounded bg-amber-100 text-amber-900 font-bold text-[10px]"
                  >
                    ⚠️ Revisar
                  </span>
                  <span v-else class="text-slate-400">—</span>
                </td>
                <td class="py-2.5 px-3 text-right">
                  <button
                    @click.stop="abrirRowPdf('normativa', row)"
                    class="p-1 rounded hover:bg-slate-200 text-primary"
                    title="Ver en PDF"
                  >
                    <ExternalLink class="w-4 h-4" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  Loader2,
  AlertTriangle,
  FileSpreadsheet,
  ExternalLink,
} from 'lucide-vue-next'
import { useAppStore } from '@/stores/useAppStore'

const store = useAppStore()
const activeTab = ref<'via1' | 'via2'>('via1')

const filteredV1 = computed(() => {
  if (!store.runStatus) return []
  let list = store.runStatus.vista_manual || []
  if (store.filterSoloRevision) {
    list = list.filter(r => r.requiere_revision_manual)
  }
  return list
})

const filteredV2 = computed(() => {
  if (!store.runStatus) return []
  let list = store.runStatus.vista_normativa || []
  if (store.filterSoloRevision) {
    list = list.filter(r => r.requiere_revision_manual)
  }
  return list
})

function formatPercent(val?: number): string {
  if (val === undefined || val === null) return '0.0%'
  return (val * 100).toFixed(1) + '%'
}

function formatList(val: any): string {
  if (Array.isArray(val)) return val.join(', ') || '—'
  return String(val || '—')
}

function nivelClass(nivel?: string): string {
  const n = String(nivel).toLowerCase()
  if (n === 'cumple') return 'bg-emerald-100 text-emerald-800'
  if (n === 'parcial') return 'bg-amber-100 text-amber-800'
  if (n === 'omision') return 'bg-rose-100 text-rose-800'
  return 'bg-slate-100 text-slate-800'
}

function abrirRowPdf(tipo: 'normativa' | 'manual', row: any) {
  const docId = row.doc_id || row.seccion_doc_id || row.articulo_doc_id
  const page = row.pagina_inicio || row.pagina || 1
  store.openPdfViewer(tipo, docId, page, row.bbox, row.jerarquia || row.encabezado)
}
</script>
