// frontend/src/App.tsx
import { useEffect } from 'react'
import { AlertTriangle, Loader2, X } from 'lucide-react'
import Header from '@/components/layout/Header'
import Stepper from '@/components/layout/Stepper'
import Step1Documents from '@/components/steps/Step1Documents'
import Step2Index from '@/components/steps/Step2Index'
import Step3Scope from '@/components/steps/Step3Scope'
import Step4Results from '@/components/steps/Step4Results'
import { useAppStore } from '@/store/useAppStore'

/** Interfaz mínima de prueba: los 4 pasos del pipeline, sin login, visor PDF ni inspector. */
export default function App() {
  const authChecking = useAppStore((s) => s.authChecking)
  const authBlocked = useAppStore((s) => s.authBlocked)
  const currentStep = useAppStore((s) => s.currentStep)
  const error = useAppStore((s) => s.error)
  const clearError = useAppStore((s) => s.clearError)

  useEffect(() => {
    const { fetchHealth, checkAuth } = useAppStore.getState()
    void fetchHealth().then(checkAuth)
  }, [])

  return (
    <div className="min-h-screen flex flex-col bg-canvas text-content-main">
      <Header />

      {authChecking ? (
        <div className="flex-1 flex flex-col items-center justify-center p-12 space-y-3">
          <Loader2 className="w-8 h-8 text-primary animate-spin" />
          <span className="text-xs text-content-muted">Conectando con la API...</span>
        </div>
      ) : authBlocked ? (
        <main className="flex-1 max-w-2xl w-full mx-auto p-8">
          <div role="alert" className="p-5 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 space-y-2 text-sm">
            <p className="font-bold flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-600" /> La API exige sesión
            </p>
            <p>
              Esta interfaz mínima no tiene pantalla de acceso. Arranca el backend con{' '}
              <code className="font-mono bg-amber-100 px-1 rounded">AUTH_ENABLED=false</code> para probarla.
            </p>
          </div>
        </main>
      ) : (
        <>
          <Stepper />
          <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
            {error && (
              <div
                role="alert"
                className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-900 text-xs sm:text-sm flex items-start justify-between gap-3"
              >
                <span className="flex items-start gap-2">
                  <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
                  <span>{error}</span>
                </span>
                <button onClick={clearError} className="text-rose-700 hover:text-rose-900" title="Cerrar">
                  <X className="w-4 h-4" />
                </button>
              </div>
            )}
            {currentStep === 1 && <Step1Documents />}
            {currentStep === 2 && <Step2Index />}
            {currentStep === 3 && <Step3Scope />}
            {currentStep === 4 && <Step4Results />}
          </main>
        </>
      )}

      <footer className="bg-surface border-t border-border py-4 px-6 text-center text-xs text-content-muted">
        <p>Comparador de Normativas vs Manuales Internos · interfaz mínima de prueba</p>
      </footer>
    </div>
  )
}

// frontend/src/App.vue
<template>
  <div class="min-h-screen flex flex-col bg-canvas text-content-main selection:bg-primary-light selection:text-primary">
    <!-- Encabezado Principal -->
    <Header />

    <!-- Estado de carga inicial de autenticación -->
    <div v-if="store.authChecking" class="flex-1 flex flex-col items-center justify-center p-12 space-y-3">
      <Loader2 class="w-8 h-8 text-primary animate-spin" />
      <span class="text-xs text-content-muted">Verificando sesión segura...</span>
    </div>

    <!-- Pantalla de Login si no está autenticado -->
    <LoginCard v-else-if="!store.isAuthenticated" />

    <!-- Flujo completo de aplicación si está autenticado -->
    <template v-else>
      <!-- Barra de Pasos (Stepper) -->
      <Stepper />

      <!-- Área de Contenido Principal -->
      <main class="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
        <Step1Documents v-if="store.currentStep === 1" />
        <Step2Index v-else-if="store.currentStep === 2" />
        <Step3Scope v-else-if="store.currentStep === 3" />
        <Step4Results v-else-if="store.currentStep === 4" />
      </main>
    </template>

    <!-- Modal de Visor de PDF (Pantalla Completa en Móvil / Gran Modal en Desktop e iPad) -->
    <div
      v-if="store.showPdfModal && store.activePdf"
      class="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-6 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200"
    >
      <div class="w-full max-w-5xl h-[92vh] flex flex-col rounded-xl overflow-hidden shadow-2xl">
        <PdfViewer
          :tipo="store.activePdf.tipo"
          :doc-id="store.activePdf.docId"
          :initial-page="store.activePdf.page"
          :bbox="store.activePdf.bbox"
          :titulo="store.activePdf.titulo"
          :closable="true"
          @close="store.showPdfModal = false"
        />
      </div>
    </div>

    <!-- Drawer Lateral de Inspector de Chunks -->
    <div
      v-if="store.showChunkDrawer && store.activeChunk"
      class="fixed inset-0 z-40 flex justify-end bg-slate-950/40 backdrop-blur-xs"
      @click.self="store.showChunkDrawer = false"
    >
      <div class="w-full sm:w-[480px] h-full shadow-2xl animate-in slide-in-from-right duration-250">
        <ChunkInspector
          :chunk="store.activeChunk"
          :closable="true"
          @close="store.showChunkDrawer = false"
        />
      </div>
    </div>

    <!-- Pie de Página -->
    <footer class="bg-surface border-t border-border py-4 px-6 text-center text-xs text-content-muted">
      <p>Comparador de Normativas vs Manuales Internos · Fase 2 (Vue 3 + FastAPI + PDF.js)</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { Loader2 } from 'lucide-vue-next'
import Header from '@/components/layout/Header.vue'
import Stepper from '@/components/layout/Stepper.vue'
import LoginCard from '@/components/layout/LoginCard.vue'
import Step1Documents from '@/components/steps/Step1Documents.vue'
import Step2Index from '@/components/steps/Step2Index.vue'
import Step3Scope from '@/components/steps/Step3Scope.vue'
import Step4Results from '@/components/steps/Step4Results.vue'
import PdfViewer from '@/components/viewer/PdfViewer.vue'
import ChunkInspector from '@/components/viewer/ChunkInspector.vue'
import { useAppStore } from '@/stores/useAppStore'

const store = useAppStore()

onMounted(async () => {
  await store.fetchHealth()
  await store.checkAuth()
})
</script>
